use_frameworks!

platform :ios, '8.0'

target 'JXEfficient' do
  pod 'JXEfficient', :path => '../'
  
  pod 'Masonry',  '1.1.0'
  pod 'SDWebImage', '4.4.3'

  target 'JXEfficient_Tests' do
    inherit! :search_paths

    
  end
end
