use_frameworks!

platform :ios, '9.0'

target 'JXEfficient' do
  pod 'JXEfficient', :path => '../'
  
  pod 'Masonry'
  pod 'SDWebImage', '5.10.2'

  target 'JXEfficient_Tests' do
    inherit! :search_paths

    
  end
end
